name: build and deploy app
on: [push,pull_request]

jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
        - name: pulling github repo
          uses: actions/checkout@v2
        - name: installing nodejs
          uses: actions/setup-node@v2
          with:
            node-version: 14
        - name: Install dependencies
          run: npm install package.json
        - name: Set up Docker
          uses: docker/setup-buildx-action@v1
        - name: docker build
          run: docker build -t docker-image .
        - name: Save Docker Image as Artifact
          uses: actions/upload-artifact@v2
          with:
            name: docker-image
            path: /var/lib/docker/image/overlay2/imagedb/content/sha256/docker-image
